// data.js
const fullWordBank = {
    "L1": [
        { id: 1, word: "dress", q: "Amy bought a fashionable _______ for her birthday party.", t: "洋裝", sentenceTranslation: "Amy 買了一件時尚洋裝。" },
        { id: 2, word: "on sale", q: "The clothes in this shop are _______, so they're cheaper now.", t: "特價", sentenceTranslation: "這間商店的衣服在特價。" },
        { id: 3, word: "shirt", q: "Matthew is wearing a blue _______ to work.", t: "襯衫", sentenceTranslation: "Matthew 穿了一件藍色襯衫去工作。" },
        { id: 4, word: "shorts", q: "Larry usually wears _______ in the summer.", t: "短褲", sentenceTranslation: "Larry 通常在夏天穿短褲。" },
        { id: 5, word: "jeans", q: "Nick spent three thousand NT dollars on this pair of _______.", t: "牛仔褲", sentenceTranslation: "Nick 花了三千元買這條牛仔褲。" },
        { id: 6, word: "sweater", q: "Jennifer is wearing jeans and a _______ today.", t: "毛衣", sentenceTranslation: "Jennifer 今天穿了牛仔褲與一件毛衣。" },
        { id: 7, word: "jacket", q: "It's cold outside. Put on your _______.", t: "夾克", sentenceTranslation: "外面很冷。穿上你的夾克。" },
        { id: 8, word: "skirt", q: "This _______ comes in three colors: red, black, and brown.", t: "裙子", sentenceTranslation: "這條裙子有三種顏色。" },
        { id: 9, word: "ring", q: "Patty is wearing a _______ on her middle finger.", t: "戒指", sentenceTranslation: "Patty 的中指戴著一枚戒指。" },
        { id: 10, word: "socks", q: "Lisa never wears shoes without _______.", t: "襪子", sentenceTranslation: "Lisa 從未穿鞋不穿襪。" },
        { id: 11, word: "cap", q: "The man is wearing a black _______.", t: "(有帽舌的)帽子", sentenceTranslation: "這名男子戴著黑色帽子。" },
        { id: 12, word: "tie", q: "Michael has to wear a shirt and _______ at work.", t: "領帶", sentenceTranslation: "Michael 上班必須穿襯衫打領帶。" },
        { id: 13, word: "belt", q: "Ivy bought her father a _______ as his birthday gift.", t: "腰帶", sentenceTranslation: "Ivy 買了條腰帶給她爸爸當生日禮物。" },
        { id: 14, word: "pants", q: "These _______ were too long for me, so I didn't buy them.", t: "長褲", sentenceTranslation: "這些長褲對我來說太長了。" },
        { id: 15, word: "wallet", q: "Jason had only twenty NT dollars in his _______.", t: "錢包", sentenceTranslation: "Jason 的錢包裡只有二十元。" },
        { id: 16, word: "a pair of", q: "I bought _______ pants on the Internet last week.", t: "一件(褲子);一雙(鞋)", sentenceTranslation: "我上週在網路上買了一件長褲。" },
        { id: 17, word: "gloves", q: "Emily bought a pair of _______ in the department store.", t: "手套", sentenceTranslation: "Emily 在百貨公司買了一雙手套。" },
        { id: 18, word: "try on", q: "This jacket is too big. Can I _______ a smaller one?", t: "試穿", sentenceTranslation: "這件夾克太大了。我可以試穿小一點的嗎？" },
        { id: 19, word: "take off", q: "Please _______ your hat when you go into the building.", t: "脫下", sentenceTranslation: "當你進入這棟建築物時，請脫掉你的帽子。" },
        { id: 20, word: "is full of", q: "This restaurant is popular, so it _______ always _______ _______ people.", t: "充滿", sentenceTranslation: "這間餐廳受歡迎，所以它總是充滿了人。" },
        { id: 21, word: "fashionable", q: "Your jeans are so _______. Where did you get them?", t: "流行的;時尚的", sentenceTranslation: "你的牛仔褲好時尚。" },
        { id: 22, word: "as as", q: "Exercise is _______ important _______ a good night's sleep.", t: "as... as... (如同...一樣地)", sentenceTranslation: "運動如同一夜好眠一樣重要。" },
        { id: 23, word: "than", q: "Your bag is heavier _______ mine.", t: "比;比較", sentenceTranslation: "你的包包比我的重。" },
        { id: 24, word: "already", q: "Mia wants more shoes, but she _______ has 50 pairs.", t: "已經", sentenceTranslation: "Mia 想要買更多鞋子，但她已經有 50 雙了。" },
        { id: 25, word: "fashion", q: "Short hair is in _______ for girls now.", t: "流行;時尚", sentenceTranslation: "現在女孩子流行留短髮。" },
        { id: 26, word: "medium", q: "Ann: What size do you wear? Ben: I wear a _______.", t: "中等尺寸;中等的", sentenceTranslation: "我穿中號。" },
        { id: 27, word: "fitting room", q: "Paul is trying on the jeans in the _______.", t: "試衣間", sentenceTranslation: "Paul 正在試衣間試穿牛仔褲。" },
        { id: 28, word: "agree", q: "Ed: I _______. He is a nice person.", t: "同意", sentenceTranslation: "Ed: 我同意。他是一個好人。" },
        { id: 29, word: "comfortable", q: "I am not _______ in these shoes. They are too small.", t: "舒服的", sentenceTranslation: "我穿這雙鞋不舒服。它們太小了。" },
        { id: 30, word: "light", q: "This jacket is really _______ and comfortable.", t: "輕薄的", sentenceTranslation: "這件夾克非常輕薄且舒適。" },
        { id: 31, word: "recycle", q: "Can you _______ old clothes?", t: "回收", sentenceTranslation: "你可以回收舊衣服嗎？" },
        { id: 32, word: "planets", q: "Is there life on other _______?", t: "星球", sentenceTranslation: "其他星球上有生物嗎？" },
        { id: 33, word: "business", q: "Helen started a new _______ with her friends.", t: "公司;生意", sentenceTranslation: "Helen 和她的朋友們開始了新的事業。" },
        { id: 34, word: "customers", q: "The department store is full of _______.", t: "顧客", sentenceTranslation: "這間百貨公司充滿了顧客。" },
        { id: 35, word: "Actually", q: "_______, I have a test tomorrow.", t: "實際上", sentenceTranslation: "實際上，我明天有個考試。" },
        { id: 36, word: "owner", q: "Mars is the _______ of this white car.", t: "所有人", sentenceTranslation: "Mars 是這輛白色汽車的車主。" },
        { id: 37, word: "items", q: "The restaurant has a long menu of about 60 _______.", t: "項目", sentenceTranslation: "這間餐廳的菜單有多達約 60 個品項。" },
        { id: 38, word: "fresh", q: "Would you like some _______ strawberries?", t: "新鮮的", sentenceTranslation: "你想要來一些新鮮的草莓嗎？" },
        { id: 39, word: "means", q: "What does 'clever' mean? It _______ 'smart'.", t: "意指", sentenceTranslation: "它意指「聰明的」。" },
        { id: 40, word: "Earth", q: "There are many beautiful animals on _______.", t: "地球", sentenceTranslation: "地球上有許多美麗的動物。" },
        { id: 41, word: "turned into", q: "The woman _______ the old coat _______ a new bag.", t: "(使)成為", sentenceTranslation: "這位女士把舊外套改造成了一個新包包。" }
    ],
    "L2": [
        { id: 201, word: "sofa", q: "My pet cat is under the _______.", t: "沙發", sentenceTranslation: "我的寵物貓在沙發下面。" },
        { id: 202, word: "lamp", q: "Turn on the desk _______ before you start reading.", t: "桌燈", sentenceTranslation: "開始閱讀前先打開桌燈。" },
        { id: 203, word: "piano", q: "Rebecca practices the _______ every night.", t: "鋼琴", sentenceTranslation: "Rebecca 每晚練習鋼琴。" },
        { id: 204, word: "radio", q: "My grandpa used to listen to the _______ every morning.", t: "收音機", sentenceTranslation: "我的爺爺過去習慣每天早上聽收音機。" },
        { id: 205, word: "washing machine", q: "Nick put his dirty clothes in the _______.", t: "洗衣機", sentenceTranslation: "Nick 將他的髒衣服放進洗衣機裡。" },
        { id: 206, word: "refrigerator", q: "We put milk in the _______ to stop it from going bad.", t: "冰箱", sentenceTranslation: "我們將牛奶放在冰箱內以免壞掉。" },
        { id: 207, word: "violin", q: "It is not easy to learn to play the _______.", t: "小提琴", sentenceTranslation: "要學會拉小提琴不容易。" },
        { id: 208, word: "bow", q: "The seller showed us the best _______ in his store.", t: "琴弓", sentenceTranslation: "那個賣家給我們看他店裡最好的琴弓。" },
        { id: 209, word: "tape", q: "I need some _______ to fix my broken book.", t: "膠帶", sentenceTranslation: "我需要一些膠帶來修補我破掉的書。" },
        { id: 210, word: "concert", q: "I'll play the piano at the _______ next Saturday.", t: "音樂會", sentenceTranslation: "我將在下週六的音樂會上彈鋼琴。" },
        { id: 211, word: "turned on", q: "I _______ the TV to watch my favorite show.", t: "打開(開關)", sentenceTranslation: "我打開電視看我最愛的節目。" },
        { id: 212, word: "turn off", q: "Remember to _______ the lamp before you leave the room.", t: "關掉(開關)", sentenceTranslation: "你離開房間之前記得關燈。" },
        { id: 213, word: "screen", q: "The photo on your cellphone _______ is beautiful.", t: "螢幕", sentenceTranslation: "你手機螢幕上的這張相片很漂亮。" },
        { id: 214, word: "power bank", q: "Fred: Don't worry. You can use my _______.", t: "行動電源", sentenceTranslation: "Fred: 別擔心。你可以用我的行動電源。" },
        { id: 215, word: "out of order", q: "The toilet is _______. We can't use it now.", t: "故障", sentenceTranslation: "那個馬桶故障了。我們現在無法使用它。" },
        { id: 216, word: "sweetest", q: "For Debbie, being a mother is the _______ thing in the world.", t: "最甜蜜的", sentenceTranslation: "對 Debbie 來說，當媽媽是世界上最甜蜜的事了。" },
        { id: 217, word: "most", q: "Emma is the _______ popular student in my class.", t: "最", sentenceTranslation: "Emma 是我班上最受歡迎的學生。" },
        { id: 218, word: "envelope", q: "I wrote a letter to my mom and put it in an _______.", t: "信封", sentenceTranslation: "我寫了一封信給媽媽並把它放在信封裡。" },
        { id: 219, word: "used to", q: "I _______ take photos with a camera, but now I use my smartphone.", t: "過去經常", sentenceTranslation: "我過去經常用照相機拍照，但是現在我用我的智慧型手機。" },
        { id: 220, word: "useful", q: "This book is very _______ to me. I need it to do my science report.", t: "有用的", sentenceTranslation: "這本書對我來說很有用。我需要它來做我的科學報告。" },
        { id: 221, word: "fake", q: "The woman used a _______ name at the hotel.", t: "假的", sentenceTranslation: "那個女子在飯店使用了假名。" },
        { id: 222, word: "deal", q: "The jeans only cost NT$200. It's a great _______.", t: "划算的交易", sentenceTranslation: "這條牛仔褲只要新臺幣 200 元。很划算。" },
        { id: 223, word: "scams", q: "There are a lot of online stores, and some are _______. You need to be careful.", t: "詐騙", sentenceTranslation: "網路商店很多，有些是詐騙。你要小心。" },
        { id: 224, word: "strange", q: "There is a _______ woman behind the tree. Who is she?", t: "陌生的", sentenceTranslation: "那棵樹後面有個陌生的女人。她是誰？" },
        { id: 225, word: "joke", q: "This is not a _______, and we must act right now.", t: "玩笑", sentenceTranslation: "這不是玩笑，我們必須立即採取行動。" },
        { id: 226, word: "seller", q: "They are the largest _______ of books in Taiwan.", t: "銷售商", sentenceTranslation: "他們是臺灣最大的書本銷售商。" },
        { id: 227, word: "anymore", q: "Sam doesn't live here _______.", t: "再也(不)", sentenceTranslation: "Sam 已經不住在這裡了。" },
        { id: 228, word: "stop by", q: "I will _______ your house tomorrow after lunch.", t: "順道拜訪", sentenceTranslation: "明天午餐後我會順道拜訪你家。" },
        { id: 229, word: "pick up", q: "Can you _______ the tickets on your way home from work?", t: "取(票/物)", sentenceTranslation: "你能在下班回家的路上取票嗎？" },
        { id: 230, word: "trick", q: "Sue is planning to play a _______ on her brother.", t: "捉弄", sentenceTranslation: "Sue 正計劃捉弄她的哥哥。" },
        { id: 231, word: "billion", q: "There are over one _______ people in India.", t: "十億", sentenceTranslation: "印度有超過十億人口。" },
        { id: 232, word: "part", q: "Jerry: What's your favorite _______ of this song?", t: "部分", sentenceTranslation: "Jerry: 你最喜愛這首歌的哪個部分？" },
        { id: 233, word: "tips", q: "My mother gave me some useful _______ for buying watermelons.", t: "提示", sentenceTranslation: "我媽媽給我一些挑選西瓜有用的提示。" },
        { id: 234, word: "information", q: "I need some _______ about good restaurants in Taipei.", t: "資訊", sentenceTranslation: "我需要一些關於臺北好的餐廳的資訊。" },
        { id: 235, word: "strangers", q: "Elisa told her daughter not to talk to _______.", t: "陌生人", sentenceTranslation: "Elisa 告訴她的女兒不要跟陌生人說話。" },
        { id: 236, word: "secrets", q: "John and his wife have no _______ from each other.", t: "祕密", sentenceTranslation: "John 和他的老婆之間沒有祕密。" },
        { id: 237, word: "words", q: "Those _______ are too difficult for Mike.", t: "字", sentenceTranslation: "這些字對 Mike 來說太難了。" },
        { id: 238, word: "sentence", q: "I don't know the meaning of this Japanese _______.", t: "句子", sentenceTranslation: "我不知道這句日文是什麼意思。" },
        { id: 239, word: "tell from", q: "Ms. Lee can't _______ Paul _______ his brother Mark.", t: "區分", sentenceTranslation: "李小姐無法區分 Paul 和他弟弟 Mark。" },
        { id: 240, word: "stays", q: "The department store _______ open until 10 p.m.", t: "保持", sentenceTranslation: "這間百貨公司營業至晚上 10 點。" }
    ]
};