// data.js
const wordBank = [
    { id: 1, word: "dress", q: "Amy bought a fashionable _______ for her birthday party.", t: "Amy 買了一件時尚洋裝。" },
    { id: 2, word: "on sale", q: "The clothes in this shop are _______, so they're cheaper now.", t: "這間商店的衣服在特價。" },
    { id: 3, word: "shirt", q: "Matthew is wearing a blue _______ to work.", t: "Matthew 穿了一件藍色襯衫去工作。" },
    { id: 4, word: "shorts", q: "Larry usually wears _______ in the summer.", t: "Larry 通常在夏天穿短褲。" },
    { id: 5, word: "jeans", q: "Nick spent three thousand NT dollars on this pair of _______.", t: "Nick 花了三千元買這條牛仔褲。" },
    { id: 6, word: "sweater", q: "Jennifer is wearing jeans and a _______ today.", t: "Jennifer 今天穿了牛仔褲與一件毛衣。" },
    { id: 7, word: "jacket", q: "It's cold outside. Put on your _______.", t: "外面很冷。穿上你的夾克。" },
    { id: 8, word: "skirt", q: "This _______ comes in three colors: red, black, and brown.", t: "這條裙子有三種顏色。" },
    { id: 9, word: "ring", q: "Patty is wearing a _______ on her middle finger.", t: "Patty 的中指戴著一枚戒指。" },
    { id: 10, word: "socks", q: "Lisa never wears shoes without _______.", t: "Lisa 從未穿鞋不穿襪。" },
    { id: 11, word: "cap", q: "The man is wearing a black _______.", t: "這名男子戴著黑色帽子。" },
    { id: 12, word: "tie", q: "Michael has to wear a shirt and _______ at work.", t: "Michael 上班必須穿襯衫打領帶。" },
    { id: 13, word: "belt", q: "Ivy bought her father a _______ as his birthday gift.", t: "Ivy 買了條腰帶給她爸爸當生日禮物。" },
    { id: 14, word: "pants", q: "These _______ were too long for me, so I didn't buy them.", t: "這些長褲對我來說太長了。" },
    { id: 15, word: "wallet", q: "Jason had only twenty NT dollars in his _______.", t: "Jason 的錢包裡只有二十元。" },
    { id: 16, word: "a pair of", q: "I bought _______ pants on the Internet last week.", t: "我上週在網路上買了一件長褲。" },
    { id: 17, word: "gloves", q: "Emily bought a pair of _______ in the department store.", t: "Emily 在百貨公司買了一雙手套。" },
    { id: 18, word: "try on", q: "This jacket is too big. Can I _______ a smaller one?", t: "這件夾克太大了。我可以試穿小一點的嗎？" },
    { id: 19, word: "take off", q: "Please _______ your hat when you go into the building.", t: "當你進入這棟建築物時，請脫掉你的帽子。" },
    { id: 20, word: "is full of", q: "This restaurant is popular, so it _______ always _______  _______ people.", t: "這間餐廳受歡迎，所以它總是充滿了人。" },
    { id: 21, word: "fashionable", q: "Your jeans are so _______. Where did you get them?", t: "你的牛仔褲好時尚。" },
    { id: 22, word: "as; as", q: "Exercise is _______ important _______ a good night's sleep.", t: "運動如同一夜好眠一樣重要。" },
    { id: 23, word: "than", q: "Your bag is heavier _______ mine.", t: "你的包包比我的重。" },
    { id: 24, word: "already", q: "Mia wants more shoes, but she _______ has 50 pairs.", t: "Mia 想要買更多鞋子，但她已經有 50 雙了。" },
    { id: 25, word: "fashion", q: "Short hair is in _______ for girls now.", t: "現在女孩子流行留短髮。" },
    { id: 26, word: "medium", q: "Ann: What size do you wear? Ben: I wear a _______.", t: "我穿中號。" },
    { id: 27, word: "fitting room", q: "Paul is trying on the jeans in the _______.", t: "Paul 正在試衣間試穿牛仔褲。" },
    { id: 28, word: "agree", q: "Ed: I _______. He is a nice person.", t: "Ed: 我同意。他是一個好人。" },
    { id: 29, word: "comfortable", q: "I am not _______ in these shoes. They are too small.", t: "我穿這雙鞋不舒服。它們太小了。" },
    { id: 30, word: "light", q: "This jacket is really _______ and comfortable.", t: "這件夾克非常輕薄且舒適。" },
    { id: 31, word: "recycle", q: "Can you _______ old clothes?", t: "你可以回收舊衣服嗎？" },
    { id: 32, word: "planets", q: "Is there life on other _______?", t: "其他星球上有生物嗎？" },
    { id: 33, word: "business", q: "Helen started a new _______ with her friends.", t: "Helen 和她的朋友們開始了新的事業。" },
    { id: 34, word: "customers", q: "The department store is full of _______.", t: "這間百貨公司充滿了顧客。" },
    { id: 35, word: "Actually", q: "_______, I have a test tomorrow.", t: "實際上，我明天有個考試。" },
    { id: 36, word: "owner", q: "Mars is the _______ of this white car.", t: "Mars 是這輛白色汽車的車主。" },
    { id: 37, word: "items", q: "The restaurant has a long menu of about 60 _______.", t: "這間餐廳的菜單有多達約 60 個品項。" },
    { id: 38, word: "fresh", q: "Would you like some _______ strawberries?", t: "你想要來一些新鮮的草莓嗎？" },
    { id: 39, word: "means", q: "What does 'clever' mean? It _______ 'smart'.", t: "它意指「聰明的」。" },
    { id: 40, word: "Earth", q: "There are many beautiful animals on _______.", t: "地球上有許多美麗的動物。" },
    { id: 41, word: "turned into", q: "The woman _______ the old coat _______ a new bag.", t: "這位女士把舊外套改造成了一個新包包。" }
];