// data.js
const fullWordBank = {
    "L1": [
        { id: 1, word: "dress", q: "Amy bought a fashionable _______ for her birthday party.", t: "洋裝", sentenceTranslation: "Amy 買了一件時尚洋裝。" },
        { id: 2, word: "on sale", q: "The clothes in this shop are _______ _______, so they're cheaper now.", t: "特價", sentenceTranslation: "這間商店的衣服在特價。" },
        { id: 3, word: "shirt", q: "Matthew is wearing a blue _______ to work.", t: "襯衫", sentenceTranslation: "Matthew 穿了一件藍色襯衫去工作。" },
        { id: 4, word: "shorts", q: "Larry usually wears _______ in the summer.", t: "短褲", sentenceTranslation: "Larry 通常在夏天穿短褲。" },
        { id: 5, word: "jeans", q: "Nick spent three thousand NT dollars on this pair of _______.", t: "牛仔褲", sentenceTranslation: "Nick 花了三千元買這條牛仔褲。" },
        { id: 6, word: "sweater", q: "Jennifer is wearing jeans and a _______ today.", t: "毛衣", sentenceTranslation: "Jennifer 今天穿了牛仔褲與一件毛衣。" },
        { id: 7, word: "jacket", q: "It's cold outside. Put on your _______.", t: "夾克", sentenceTranslation: "外面很冷。穿上你的夾克。" },
        { id: 8, word: "skirt", q: "This _______ comes in three colors: red, black, and brown.", t: "裙子", sentenceTranslation: "這條裙子有三種顏色。" },
        { id: 9, word: "ring", q: "Patty is wearing a _______ on her middle finger.", t: "戒指", sentenceTranslation: "Patty 的中指戴著一枚戒指。" },
        { id: 10, word: "socks", q: "Lisa never wears shoes without _______.", t: "襪子", sentenceTranslation: "Lisa 從未穿鞋不穿襪。" },
        { id: 11, word: "cap", q: "The man is wearing a black _______.", t: "(有帽舌的)帽子", sentenceTranslation: "這名男子戴著黑色帽子。" },
        { id: 12, word: "tie", q: "Michael has to wear a shirt and _______ at work.", t: "領帶", sentenceTranslation: "Michael 上班必須穿襯衫打領帶。" },
        { id: 13, word: "belt", q: "Ivy bought her father a _______ as his birthday gift.", t: "腰帶", sentenceTranslation: "Ivy 買了條腰帶給她爸爸當生日禮物。" },
        { id: 14, word: "pants", q: "These _______ were too long for me, so I didn't buy them.", t: "長褲", sentenceTranslation: "這些長褲對我來說太長了。" },
        { id: 15, word: "wallet", q: "Jason had only twenty NT dollars in his _______.", t: "錢包", sentenceTranslation: "Jason 的錢包裡只有二十元。" },
        { id: 16, word: "a pair of", q: "I bought _______ _______ _______ pants on the Internet last week.", t: "一件(褲子);一雙(鞋)", sentenceTranslation: "我上週在網路上買了一件長褲。" },
        { id: 17, word: "gloves", q: "Emily bought a pair of _______ in the department store.", t: "手套", sentenceTranslation: "Emily 在百貨公司買了一雙手套。" },
        { id: 18, word: "try on", q: "This jacket is too big. Can I _______ _______ a smaller one?", t: "試穿", sentenceTranslation: "這件夾克太大了。我可以試穿小一點的嗎？" },
        { id: 19, word: "take off", q: "Please _______ _______ your hat when you go into the building.", t: "脫下", sentenceTranslation: "當你進入這棟建築物時，請脫掉你的帽子。" },
        { id: 20, word: "is full of", q: "This restaurant is popular, so it _______ always _______ _______ people.", t: "充滿", sentenceTranslation: "這間餐廳受歡迎，所以它總是充滿了人。" },
        { id: 21, word: "fashionable", q: "Your jeans are so _______. Where did you get them?", t: "流行的;時尚的", sentenceTranslation: "你的牛仔褲好時尚。" },
        { id: 22, word: "as as", q: "Exercise is _______ important _______ a good night's sleep.", t: "as... as... (如同...一樣地)", sentenceTranslation: "運動如同一夜好眠一樣重要。" },
        { id: 23, word: "than", q: "Your bag is heavier _______ mine.", t: "比;比較", sentenceTranslation: "你的包包比我的重。" },
        { id: 24, word: "already", q: "Mia wants more shoes, but she _______ has 50 pairs.", t: "已經", sentenceTranslation: "Mia 想要買更多鞋子，但她已經有 50 雙了。" },
        { id: 25, word: "fashion", q: "Short hair is in _______ for girls now.", t: "流行;時尚", sentenceTranslation: "現在女孩子流行留短髮。" },
        { id: 26, word: "medium", q: "Ann: What size do you wear? Ben: I wear a _______.", t: "中等尺寸;中等的", sentenceTranslation: "我穿中號。" },
        { id: 27, word: "fitting room", q: "Paul is trying on the jeans in the _______ _______.", t: "試衣間", sentenceTranslation: "Paul 正在試衣間試穿牛仔褲。" },
        { id: 28, word: "agree", q: "Ed: I _______. He is a nice person.", t: "同意", sentenceTranslation: "Ed: 我同意。他是一個好人。" },
        { id: 29, word: "comfortable", q: "I am not _______ in these shoes. They are too small.", t: "舒服的", sentenceTranslation: "我穿這雙鞋不舒服。它們太小了。" },
        { id: 30, word: "light", q: "This jacket is really _______ and comfortable.", t: "輕薄的", sentenceTranslation: "這件夾克非常輕薄且舒適。" },
        { id: 31, word: "recycle", q: "Can you _______ old clothes?", t: "回收", sentenceTranslation: "你可以回收舊衣服嗎？" },
        { id: 32, word: "planets", q: "Is there life on other _______?", t: "星球", sentenceTranslation: "其他星球上有生物嗎？" },
        { id: 33, word: "business", q: "Helen started a new _______ with her friends.", t: "公司;生意", sentenceTranslation: "Helen 和她的朋友們開始了新的事業。" },
        { id: 34, word: "customers", q: "The department store is full of _______.", t: "顧客", sentenceTranslation: "這間百貨公司充滿了顧客。" },
        { id: 35, word: "Actually", q: "_______, I have a test tomorrow.", t: "實際上", sentenceTranslation: "實際上，我明天有個考試。" },
        { id: 36, word: "owner", q: "Mars is the _______ of this white car.", t: "所有人", sentenceTranslation: "Mars 是這輛白色汽車的車主。" },
        { id: 37, word: "items", q: "The restaurant has a long menu of about 60 _______.", t: "項目", sentenceTranslation: "這間餐廳的菜單有多達約 60 個品項。" },
        { id: 38, word: "fresh", q: "Would you like some _______ strawberries?", t: "新鮮的", sentenceTranslation: "你想要來一些新鮮的草莓嗎？" },
        { id: 39, word: "means", q: "What does 'clever' mean? It _______ 'smart'.", t: "意指", sentenceTranslation: "它意指「聰明的」。" },
        { id: 40, word: "Earth", q: "There are many beautiful animals on _______.", t: "地球", sentenceTranslation: "地球上有許多美麗的動物。" },
        { id: 41, word: "turned into", q: "The woman _______ the old coat _______ a new bag.", t: "(使)成為", sentenceTranslation: "這位女士把舊外套改造成了一個新包包。" }
    ],
    "L2": [
        { id: 201, word: "sofa", q: "My pet cat is under the _______.", t: "沙發", sentenceTranslation: "我的寵物貓在沙發下面。" },
        { id: 202, word: "lamp", q: "Turn on the desk _______ before you start reading.", t: "桌燈", sentenceTranslation: "開始閱讀前先打開桌燈。" },
        { id: 203, word: "piano", q: "Rebecca practices the _______ every night.", t: "鋼琴", sentenceTranslation: "Rebecca 每晚練習鋼琴。" },
        { id: 204, word: "radio", q: "My grandpa used to listen to the _______ every morning.", t: "收音機", sentenceTranslation: "我的爺爺過去習慣每天早上聽收音機。" },
        { id: 205, word: "washing machine", q: "Nick put his dirty clothes in the _______ _______.", t: "洗衣機", sentenceTranslation: "Nick 將他的髒衣服放進洗衣機裡。" },
        { id: 206, word: "refrigerator", q: "We put milk in the _______ to stop it from going bad.", t: "冰箱", sentenceTranslation: "我們將牛奶放在冰箱內以免壞掉。" },
        { id: 207, word: "violin", q: "It is not easy to learn to play the _______.", t: "小提琴", sentenceTranslation: "要學會拉小提琴不容易。" },
        { id: 208, word: "bow", q: "The seller showed us the best _______ in his store.", t: "琴弓", sentenceTranslation: "那個賣家給我們看他店裡最好的琴弓。" },
        { id: 209, word: "tape", q: "I need some _______ to fix my broken book.", t: "膠帶", sentenceTranslation: "我需要一些膠帶來修補我破掉的書。" },
        { id: 210, word: "concert", q: "I'll play the piano at the _______ next Saturday.", t: "音樂會", sentenceTranslation: "我將在下週六的音樂會上彈鋼琴。" },
        { id: 211, word: "turned on", q: "I _______ _______ the TV to watch my favorite show.", t: "打開(開關)", sentenceTranslation: "我打開電視看我最愛的節目。" },
        { id: 212, word: "turn off", q: "Remember to _______ _______ the lamp before you leave the room.", t: "關掉(開關)", sentenceTranslation: "你離開房間之前記得關燈。" },
        { id: 213, word: "screen", q: "The photo on your cellphone _______ is beautiful.", t: "螢幕", sentenceTranslation: "你手機螢幕上的這張相片很漂亮。" },
        { id: 214, word: "power bank", q: "Fred: Don't worry. You can use my _______ _______.", t: "行動電源", sentenceTranslation: "Fred: 別擔心。你可以用我的行動電源。" },
        { id: 215, word: "out of order", q: "The toilet is _______ _______ _______. We can't use it now.", t: "故障", sentenceTranslation: "那個馬桶故障了。我們現在無法使用它。" },
        { id: 216, word: "sweetest", q: "For Debbie, being a mother is the _______ thing in the world.", t: "最甜蜜的", sentenceTranslation: "對 Debbie 來說，當媽媽是世界上最甜蜜的事了。" },
        { id: 217, word: "most", q: "Emma is the _______ popular student in my class.", t: "最", sentenceTranslation: "Emma 是我班上最受歡迎的學生。" },
        { id: 218, word: "envelope", q: "I wrote a letter to my mom and put it in an _______.", t: "信封", sentenceTranslation: "我寫了一封信給媽媽並把它放在信封裡。" },
        { id: 219, word: "used to", q: "I _______ _______ take photos with a camera, but now I use my smartphone.", t: "過去經常", sentenceTranslation: "我過去經常用照相機拍照，但是現在我用我的智慧型手機。" },
        { id: 220, word: "useful", q: "This book is very _______ to me. I need it to do my science report.", t: "有用的", sentenceTranslation: "這本書對我來說很有用。我需要它來做我的科學報告。" },
        { id: 221, word: "fake", q: "The woman used a _______ name at the hotel.", t: "假的", sentenceTranslation: "那個女子在飯店使用了假名。" },
        { id: 222, word: "deal", q: "The jeans only cost NT$200. It's a great _______.", t: "划算的交易", sentenceTranslation: "這條牛仔褲只要新臺幣 200 元。很划算。" },
        { id: 223, word: "scams", q: "There are a lot of online stores, and some are _______. You need to be careful.", t: "詐騙", sentenceTranslation: "網路商店很多，有些是詐騙。你要小心。" },
        { id: 224, word: "strange", q: "There is a _______ woman behind the tree. Who is she?", t: "陌生的", sentenceTranslation: "那棵樹後面有個陌生的女人。她是誰？" },
        { id: 225, word: "joke", q: "This is not a _______, and we must act right now.", t: "玩笑", sentenceTranslation: "這不是玩笑，我們必須立即採取行動。" },
        { id: 226, word: "seller", q: "They are the largest _______ of books in Taiwan.", t: "銷售商", sentenceTranslation: "他們是臺灣最大的書本銷售商。" },
        { id: 227, word: "anymore", q: "Sam doesn't live here _______.", t: "再也(不)", sentenceTranslation: "Sam 已經不住在這裡了。" },
        { id: 228, word: "stop by", q: "I will _______ _______your house tomorrow after lunch.", t: "順道拜訪", sentenceTranslation: "明天午餐後我會順道拜訪你家。" },
        { id: 229, word: "pick up", q: "Can you _______ _______ the tickets on your way home from work?", t: "取(票/物)", sentenceTranslation: "你能在下班回家的路上取票嗎？" },
        { id: 230, word: "trick", q: "Sue is planning to play a _______ on her brother.", t: "捉弄", sentenceTranslation: "Sue 正計劃捉弄她的哥哥。" },
        { id: 231, word: "billion", q: "There are over one _______ people in India.", t: "十億", sentenceTranslation: "印度有超過十億人口。" },
        { id: 232, word: "part", q: "Jerry: What's your favorite _______ of this song?", t: "部分", sentenceTranslation: "Jerry: 你最喜愛這首歌的哪個部分？" },
        { id: 233, word: "tips", q: "My mother gave me some useful _______ for buying watermelons.", t: "提示", sentenceTranslation: "我媽媽給我一些挑選西瓜有用的提示。" },
        { id: 234, word: "information", q: "I need some _______ about good restaurants in Taipei.", t: "資訊", sentenceTranslation: "我需要一些關於臺北好的餐廳的資訊。" },
        { id: 235, word: "strangers", q: "Elisa told her daughter not to talk to _______.", t: "陌生人", sentenceTranslation: "Elisa 告訴她的女兒不要跟陌生人說話。" },
        { id: 236, word: "secrets", q: "John and his wife have no _______ from each other.", t: "祕密", sentenceTranslation: "John 和他的老婆之間沒有祕密。" },
        { id: 237, word: "words", q: "Those _______ are too difficult for Mike.", t: "字", sentenceTranslation: "這些字對 Mike 來說太難了。" },
        { id: 238, word: "sentence", q: "I don't know the meaning of this Japanese _______.", t: "句子", sentenceTranslation: "我不知道這句日文是什麼意思。" },
        { id: 239, word: "tell from", q: "Ms. Lee can't _______ Paul _______ his brother Mark.", t: "區分", sentenceTranslation: "李小姐無法區分 Paul 和他弟弟 Mark。" },
        { id: 240, word: "stays", q: "The department store _______ open until 10 p.m.", t: "保持", sentenceTranslation: "這間百貨公司營業至晚上 10 點。" }
    ],
    "L3": [
    { id: 301, word: "salad", q: "I had some _______ with my steak.", t: "沙拉", sentenceTranslation: "我吃一些沙拉來搭配牛排。" },
    { id: 302, word: "hamburgers", q: "The fast food restaurant is famous for its _______.", t: "漢堡", sentenceTranslation: "這間速食店以它的漢堡聞名。" },
    { id: 303, word: "coffee", q: "Ken couldn't sleep last night because he drank too much _______.", t: "咖啡", sentenceTranslation: "Ken 昨晚無法入睡，因為他喝了太多咖啡。" },
    { id: 304, word: "steak", q: "Patty ordered a _______ at the restaurant.", t: "牛排", sentenceTranslation: "Patty 在這間餐廳點了一份牛排。" },
    { id: 305, word: "French fries", q: "I would like to order some _______ _______ without salt.", t: "薯條", sentenceTranslation: "我想要點一些無鹽薯條。" },
    { id: 306, word: "fried chicken", q: "Fred eats _______ _______ three times a week.", t: "炸雞", sentenceTranslation: "Fred 一週吃三次炸雞。" },
    { id: 307, word: "ham", q: "Dan usually has a _______ sandwich and milk for breakfast.", t: "火腿", sentenceTranslation: "Dan 通常吃火腿三明治和牛奶當早餐。" },
    { id: 308, word: "cheese", q: "Blue _______ smells bad but tastes good.", t: "起司", sentenceTranslation: "藍起司很難聞，但是嘗起來很棒。" },
    { id: 310, word: "pork", q: "Al and his family don't eat _______.", t: "豬肉", sentenceTranslation: "Al 跟他的家人不吃豬肉。" },
    { id: 311, word: "bean soup", q: "My mom's _______ _______ is delicious. We can't get enough of it.", t: "豆子湯", sentenceTranslation: "我媽媽做的豆子湯很美味。我們百吃不厭。" },
    { id: 312, word: "vegetable", q: "I had a bowl of _______ soup for lunch.", t: "蔬菜", sentenceTranslation: "我午餐喝了碗蔬菜湯。" },
    { id: 313, word: "pizza", q: "Ivy ate all the _______ without sharing it with her friends.", t: "披薩", sentenceTranslation: "Ivy 吃了整個披薩，沒有分享給她的朋友們。" },
    { id: 314, word: "buns", q: "Some people don't eat the _______ when they have a hamburger.", t: "小圓麵包", sentenceTranslation: "有些人吃漢堡時不吃小圓麵包。" },
    { id: 315, word: "toast", q: "Jim always puts butter on his _______.", t: "烤麵包片/吐司", sentenceTranslation: "Jim 總是在他的烤麵包片上加奶油。" },
    { id: 316, word: "meat", q: "Chicken is white _______, and beef is red _______.", t: "肉", sentenceTranslation: "雞肉是白肉，而牛肉是紅肉。" },
    { id: 317, word: "bread", q: "Would you like some _______ and butter?", t: "麵包", sentenceTranslation: "你要來點麵包跟奶油嗎？" },
    { id: 318, word: "walls", q: "William put pictures on the _______ of his bedroom.", t: "牆", sentenceTranslation: "William 將照片掛在他臥室的牆上。" },
    { id: 319, word: "meals", q: "Gina cooks three _______ for her family every day.", t: "三餐/餐點", sentenceTranslation: "Gina 每天幫家人煮三餐。" },
    { id: 320, word: "oil", q: "Maggie started to cook the chicken with some _______.", t: "油", sentenceTranslation: "Maggie 開始用一些油烹煮雞肉。" },
    { id: 321, word: "sounds", q: "Ian: What do you think about my plan?  Lily: It _______ good.", t: "聽起來", sentenceTranslation: "Ian：你覺得我的計畫如何？ Lily：它聽起來不錯。" },
    { id: 322, word: "weight", q: "Tommy lost a lot of _______ when he was sick.", t: "體重", sentenceTranslation: "Tommy 在他生病時體重下降許多。" },
    { id: 323, word: "smells", q: "The vegetable soup _______ good. Who made it?", t: "聞起來", sentenceTranslation: "這碗蔬菜湯聞起來很香。是誰做的？" },
    { id: 324, word: "tasted", q: "The fried rice _______ good. I couldn't stop eating it.", t: "嘗起來", sentenceTranslation: "炒飯嘗起來很棒。我一吃就停不下來。" },
    { id: 325, word: "dig in", q: "Let's _______ _______ before the food gets cold.", t: "開動", sentenceTranslation: "我們在食物變冷前開動吧。" },
    { id: 326, word: "soon", q: "Gemma is going to be a mother _______.", t: "很快", sentenceTranslation: "Gemma 很快要當媽媽了。" },
    { id: 327, word: "order", q: "Excuse me. May I take your _______, sir?", t: "點餐", sentenceTranslation: "不好意思。我可以幫你點餐嗎，先生？" },
    { id: 328, word: "putting on", q: "I don't eat a lot because I'm afraid of _______ _______ weight.", t: "增加(體重)", sentenceTranslation: "我沒有吃很多，因為我害怕體重增加。" },
    { id: 329, word: "get", q: "Eat your soup first, or it will _______ cold.", t: "變得", sentenceTranslation: "先喝湯，否則它會變冷。" },
    { id: 330, word: "noticed", q: "Zack: Dad is back.  Liza: I know. I _______ his car outside.", t: "注意到", sentenceTranslation: "Zack：爸爸回來了。 Liza：我知道。我注意到他的車在外面。" },
    { id: 331, word: "invited", q: "Jordan _______ us to his party last weekend.", t: "邀請", sentenceTranslation: "Jordan 上週末邀請我們參加他的派對。" },
    { id: 332, word: "Besides", q: "I don't want to eat out. _______, I don't have any money.", t: "而且/此外", sentenceTranslation: "我不想去外面吃。而且，我沒有半毛錢。" },
    { id: 333, word: "probably", q: "Helen likes the green T-shirt, so she will _______ buy it.", t: "也許/大概", sentenceTranslation: "Helen 喜歡這件綠色 T 恤，所以她也許會買它。" },
    { id: 334, word: "bite", q: "Nick took a _______ of the sandwich.", t: "咬/一口", sentenceTranslation: "Nick 咬了一口三明治。" },
    { id: 335, word: "stand for", q: "The flowers _______ _______ my love.", t: "代表", sentenceTranslation: "這些花代表我的愛。" },
    { id: 336, word: "matter", q: "To Julie, her children _______ the most in the world.", t: "重要/要緊", sentenceTranslation: "對 Julie 而言，她的孩子是世上最重要的。" },
    { id: 337, word: "sign", q: "The _______ on the wall says 'Wash hands before you eat.'", t: "標誌/告示", sentenceTranslation: "牆上的標誌寫著「吃東西前先洗手」。" },
    { id: 338, word: "friendly", q: "Mr. Chen's restaurant is _______. My family and I feel happy and comfortable there.", t: "令人愉快的/友善的", sentenceTranslation: "陳先生的餐廳令人愉快，我和我的家人在那裡感覺很開心也很舒服。" }
    ],
    "L4": [
    { id: 401, word: "set up", q: "It's getting dark. Let's _______ _______ camp quickly.", t: "搭(帳篷)", sentenceTranslation: "天色變暗了。我們快點搭帳篷吧。" },
    { id: 402, word: "make a fire", q: "Be careful when you _______ _______ _______.", t: "生火", sentenceTranslation: "當你生火時要小心。" },
    { id: 403, word: "boiling", q: "I am _______ water for the tea.", t: "煮沸", sentenceTranslation: "我正在將水煮沸來泡茶。" },
    { id: 404, word: "bugs", q: "James caught some _______.", t: "昆蟲", sentenceTranslation: "James 抓了一些蟲。" },
    { id: 405, word: "picnic", q: "Let's go on a _______ at the park today.", t: "野餐", sentenceTranslation: "今天我們去公園野餐吧。" },
    { id: 406, word: "hung out", q: "Dad _______ _______ the clothes to dry.", t: "晾晒", sentenceTranslation: "爸爸將衣服掛在外面晾乾。" },
    { id: 407, word: "towel", q: "Howard dried his hands with the _______.", t: "毛巾", sentenceTranslation: "Howard 用毛巾擦乾手。" },
    { id: 408, word: "lay", q: "Max _______ down and took a rest.", t: "躺下", sentenceTranslation: "Max 躺下休息。" },
    { id: 409, word: "grass", q: "The sign reads, “Keep off the _______.”", t: "草坪", sentenceTranslation: "標語上寫著：「請勿踐踏草坪」。" },
    { id: 410, word: "string lights", q: "We put _______ _______ around the trees for the party.", t: "燈串", sentenceTranslation: "我們在樹周圍掛上了繩燈，為派對做準備。" },
    { id: 411, word: "moon", q: "We can usually see a full _______ during the Mid-Autumn Festival.", t: "月亮", sentenceTranslation: "我們在中秋節通常能看見滿月。" },
    { id: 412, word: "Count", q: "_______ to ten before we start the game.", t: "數一數", sentenceTranslation: "在我們開始遊戲之前，先數到十。" },
    { id: 413, word: "packing", q: "Sandy was still _______ her bag when the taxi came.", t: "打包", sentenceTranslation: "當計程車來的時候，Sandy 還在打包她的包包。" },
    { id: 414, word: "perfect", q: "David had _______ weather during his vacation in Japan.", t: "完美的", sentenceTranslation: "David 在日本度假期間天氣很完美。" },
    { id: 415, word: "are able to", q: "The young birds _______ _______ _______ fly now.", t: "能夠", sentenceTranslation: "幼鳥現在能夠飛了。" },
    { id: 416, word: "well", q: "I didn't sleep _______ because I had a bad dream.", t: "很好地", sentenceTranslation: "我睡不好因為我做了惡夢。" },
    { id: 417, word: "loudly", q: "Sorry, I can't hear you clearly. Please speak _______.", t: "大聲地", sentenceTranslation: "抱歉，我聽不清楚。請說大聲點。" },
    { id: 418, word: "slowly", q: "The sun went down _______ behind the mountains.", t: "緩慢地", sentenceTranslation: "太陽慢慢地落到了山後。" },
    { id: 419, word: "gently", q: "Emily closed the door _______ because Tim was sleeping.", t: "輕柔地", sentenceTranslation: "Emily 輕柔地關上門，因為 Tim 正在睡覺。" },
    { id: 420, word: "smiled", q: "The old woman _______ at me after I helped her.", t: "微笑", sentenceTranslation: "這名老婦人在我協助她之後對我微笑。" },
    { id: 421, word: "hopped", q: "The boy didn't walk but _______ along the sidewalk.", t: "單腳跳躍", sentenceTranslation: "這個男孩不好好走路，卻沿著人行道單腳跳躍進。" },
    { id: 422, word: "dancing queen", q: "Ann is a _______ _______. She dances the best at school.", t: "舞后", sentenceTranslation: "Ann 是個舞后。她在學校裡舞跳得最好。" },
    { id: 423, word: "hard", q: "Tim studies _______ and plays _______.", t: "努力地", sentenceTranslation: "Tim 努力讀書也努力玩耍。" },
    { id: 424, word: "tripped", q: "Andy ran too fast and _______.", t: "絆倒", sentenceTranslation: "Andy 跑得太快然後絆倒了。" },
    { id: 425, word: "experience", q: "I took a trip to the USA last month. It was a great _______ for me.", t: "經驗", sentenceTranslation: "我上個月去美國旅行。對我來說，那是一個很棒的經驗。" },
    { id: 426, word: "diary", q: "Ben keeps a _______ about his school life.", t: "日記", sentenceTranslation: "Ben 寫日記記錄他的學校生活。" },
    { id: 427, word: "arrive", q: "Ann: What time will the train _______ in Taipei?  Ben: At five.", t: "抵達", sentenceTranslation: "Ann：火車將在幾點抵達臺北？ Ben：五點。" },
    { id: 428, word: "areas", q: "It will rain in all _______ of this country this afternoon.", t: "地區", sentenceTranslation: "今天下午這個國家的所有地區都會下雨。" },
    { id: 429, word: "successfully", q: "Paula played the piano _______ at the show.", t: "成功地", sentenceTranslation: "Paula 在這場表演中成功地演奏了鋼琴。" },
    { id: 430, word: "pot", q: "There is a _______ of chicken soup in the kitchen.", t: "鍋", sentenceTranslation: "廚房裡有一鍋雞湯。" },
    { id: 431, word: "burned", q: "Sam didn't enjoy his dinner because his steak _______.", t: "燒焦", sentenceTranslation: "Sam 不喜歡他的晚餐，因為他的牛排烤焦了。" },
    { id: 432, word: "unhappy", q: "The workers are _______ because they have to work on the weekend.", t: "不高興", sentenceTranslation: "工人們不高興，因為他們必須在週末工作。" },
    { id: 433, word: "hold", q: "The teacher will _______ a meeting with the parents next week. It is about the school trip.", t: "舉辦", sentenceTranslation: "老師下週將與家長開會，會議內容是關於校外教學的事情。" },
    { id: 434, word: "circle", q: "The sun looks like a big yellow _______ in the sky.", t: "圓圈", sentenceTranslation: "太陽看起來像天空中一個又大又黃的圓圈。" },
    { id: 435, word: "shy", q: "Harry is so _______. He seldom talks in class.", t: "害羞", sentenceTranslation: "Harry 很害羞。他在課堂上很少說話。" },
    { id: 436, word: "line", q: "Many people waited in _______ outside the bakery.", t: "隊伍", sentenceTranslation: "許多人在麵包店外排隊等候。" },
    { id: 437, word: "laughed", q: "Ivan _______ at the end of Eva’s funny story.", t: "笑", sentenceTranslation: "Ivan 在 Eva 有趣故事的結尾笑了。" },
    { id: 438, word: "anyone / anybody", q: "There isn't _______ in the classroom. Where are the students?", t: "任何人", sentenceTranslation: "教室裡沒有人。學生們在哪裡？" },
    { id: 439, word: "else", q: "You ordered the soup and the sandwich. Anything _______?", t: "其他的", sentenceTranslation: "你點了湯和三明治。還需要別的嗎？" },
    { id: 440, word: "clap", q: "At the end of the show, one man began to _______, and the others joined in.", t: "拍手", sentenceTranslation: "表演結束時，一名男子開始拍手，其他人也跟著拍手。" },
    { id: 441, word: "cheer", q: "Let's _______ for Lisa! She won first place in the race.", t: "歡呼", sentenceTranslation: "讓我們為 Lisa 加油吧！她在比賽中得了第一名。" },
    { id: 442, word: "festival", q: "Many people went to the movie _______ last night.", t: "節慶", sentenceTranslation: "昨晚有許多人去參加電影節。" },
    { id: 443, word: "heart", q: "Andrew drew a big _______ on the card to show his love for his wife.", t: "心/愛心", sentenceTranslation: "Andrew 在卡片上畫了一個大愛心，來表達他對妻子的愛。" },
    { id: 444, word: "shape", q: "Jim’s birthday cake is in the _______ of a bear.", t: "形狀", sentenceTranslation: "Jim 的生日蛋糕形狀是隻熊。" },
    { id: 445, word: "lucky", q: "Amber: Did you find a parking space?  Janet: Yes, I did! I was so _______.", t: "幸運的", sentenceTranslation: "Amber：你找到停車位了嗎？ Janet：有，我有找到。我好幸運。" }
    ]
};